# Generated by Django 3.2.12 on 2024-04-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_of_day_start', models.IntegerField(default=0, help_text='0 to dislable time of day enabeling, hour of the day 0-24')),
                ('time_of_day_end', models.IntegerField(default=0, help_text='Ignored is time_of_day_start is 0, hour of the day 0-24')),
                ('count_per_day', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('allowed_user_groups', models.ManyToManyField(help_text='blank for everyone', to='Customers.CustomerGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField(help_text='in howe-bucks')),
                ('location', models.CharField(max_length=3, unique=True)),
                ('available', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(to='Products.ProductGroup')),
            ],
        ),
    ]
